version: 0.1.5.{build}
image:
  - Visual Studio 2017
  - Ubuntu1804

configuration:
  - Debug
  - Release
  - RelWithDebInfo

platform:
  - x86
  - x64

environment:
  matrix:
    - LINKING: static
    - LINKING: shared

matrix:
  exclude:
    - image: Ubuntu1804
      platform: x86
    - image: Ubuntu1804
      LINKING: static
    - image: Ubuntu1804
      configuration: Debug
    - image: Ubuntu1804
      configuration: RelWithDebInfo
    - configuration: RelWithDebInfo
      LINKING: static

  allow_failures:
    - configuration: Debug
      LINKING: static

for:
-
  matrix:
    only:
      - image: Ubuntu1804
  
  cache:
    - vcpkg

  install:
    - git config --global user.name "Anonymous"
    - git config --global user.email "anon@example.org"
    - git clone https://github.com/Microsoft/vcpkg.git || true
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install args sf2cute
    - cd ..

  build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build .
-
  matrix:
    only:
      - image: Visual Studio 2017
  
  cache:
    - c:\tools\vcpkg\installed\

  install:
    - git config --global user.name "Anonymous"
    - git config --global user.email "anon@example.org"
    - cd C:\tools\vcpkg
    - git fetch
    - git pull
    - .\bootstrap-vcpkg.bat
    - cd %APPVEYOR_BUILD_FOLDER%
    - set TRIPLET=%PLATFORM%-windows
    - IF "%LINKING%"=="static" (set TRIPLET=%TRIPLET%-static)
    - vcpkg install --triplet %TRIPLET% args sf2cute

  build_script:
    - set GENERATOR=Visual Studio 15 2017
    - IF %PLATFORM%==x64 (set GENERATOR=%GENERATOR% Win64)
    - IF "%LINKING%"=="shared" (set ADDITIONAL=-DBUILD_SHARED_LIBS=ON)
    - IF "%LINKING%"=="static" (set ADDITIONAL=-DDMUSIC_FORCE_STATIC_CRT=ON)
    - set ADDITIONAL=%ADDITIONAL% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/install
    - mkdir build
    - cd build
    - cmake %ADDITIONAL% -DVCPKG_TARGET_TRIPLET=%TRIPLET% -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake .. -G "%GENERATOR%"
    - cmake --build . --config %CONFIGURATION% --target INSTALL
    - IF "%LINKING%"=="shared" ( (robocopy C:/Tools/vcpkg/installed/%TRIPLET%/bin %APPVEYOR_BUILD_FOLDER%/install/bin *.dll) ^& exit 0)

  after_build:
    - IF %PLATFORM%==x64 (set PLATFORM_NAME=win64)
    - IF %PLATFORM%==x86 (set PLATFORM_NAME=win32)
    - set ARCHIVE_NAME=libdmusic-%PLATFORM_NAME%-%LINKING%-%APPVEYOR_BUILD_VERSION%
    - IF %CONFIGURATION%==Debug (set ARCHIVE_NAME=%ARCHIVE_NAME%-Debug)
    - IF %CONFIGURATION%==RelWithDebInfo (set ARCHIVE_NAME=%ARCHIVE_NAME%-RelWithDebInfo)
    - 7z a %APPVEYOR_BUILD_FOLDER%/%ARCHIVE_NAME%.zip %APPVEYOR_BUILD_FOLDER%/install/*
    - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/%ARCHIVE_NAME%.zip