version: 0.0.{build}
image: Visual Studio 2017

cache:
  - C:\build_libsndfile
  - C:\build_rtaudio
  - C:\install_prefix

install:
  - git submodule update --init --recursive
  - git clone https://github.com/erikd/libsndfile C:/libsndfile
  - git clone https://github.com/thestk/rtaudio C:/rtaudio
  - mkdir C:\build_libsndfile
  - mkdir C:\build_rtaudio
  - cd C:/build_libsndfile
  - cmake -D CMAKE_INSTALL_PREFIX=C:/install_prefix C:/libsndfile
  - cmake --build . --target INSTALL -config Release
  - cd C:/build_rtaudio
  - cmake -D CMAKE_INSTALL_PREFIX=C:/install_prefix C:/rtaudio
  - cmake --build . --target INSTALL -config Release
  - cd C:/projects/libdmusic
  
build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_PREFIX_PATH=C:/install_prefix -DDMUSIC_STATIC=ON ..
  - cmake --build . --config RelWithDebInfo
  - 7z a libdmusic.zip .\bin\RelWithDebInfo\*.exe .\bin\RelWithDebInfo\*.pdb
  - appveyor PushArtifact libdmusic.zip

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/5020e3cf2a1bbb5c8247
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true