version: 0.0.{build}
image: Visual Studio 2017

cache:
  - C:\build_libsndfile
  - C:\build_rtaudio
  - C:\install_prefix

install:
  - git submodule update --init --recursive
  - .\ci\build_libsndfile.bat
  - .\ci\build_rtaudio.bat
  
build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_PREFIX_PATH=C:/install_prefix -DDMUSIC_STATIC=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:/projects/libdmusic/build/bin -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:/projects/libdmusic/build/lib -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=C:/projects/libdmusic/build/lib ..
  - cmake --build . --config RelWithDebInfo
  - 7z a libdmusic.zip .\bin\RelWithDebInfo\*.exe .\bin\RelWithDebInfo\*.pdb
  - appveyor PushArtifact libdmusic.zip

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/5020e3cf2a1bbb5c8247
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true