version: 0.1.3.{build}
image: Visual Studio 2017

cache:
  - C:\build_libsndfile_x86
  - C:\build_libsndfile_x86-64
  - C:\build_rtaudio_x86
  - C:\build_rtaudio_x86-64
  - C:\build_sf2cute_x86
  - C:\build_sf2cute_x86-64
  - C:\install_prefix_x86
  - C:\install_prefix_x86-64

install:
  - git submodule update --init --recursive
  - .\ci\build_libsndfile.bat
  - .\ci\build_rtaudio.bat
  - .\ci\build_sf2cute.bat
  
build_script:
  - mkdir build_x86
  - cd build_x86
  - cmake -DCMAKE_PREFIX_PATH=C:/install_prefix_x86 -DDMUSIC_STATIC=ON -DCMAKE_INSTALL_PREFIX=C:/install_libdmusic_x86 ..
  - cmake --build . --config RelWithDebInfo --target INSTALL
  - 7z a libdmusic-v%APPVEYOR_BUILD_VERSION%-win32-ia32.zip C:/install_libdmusic_x86/*
  - appveyor PushArtifact libdmusic-v%APPVEYOR_BUILD_VERSION%-win32-ia32.zip
  - cd ..
  - mkdir build_x86-64
  - cd build_x86-64
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:/install_prefix_x86-64 -DDMUSIC_STATIC=ON -DCMAKE_INSTALL_PREFIX=C:/install_libdmusic_x86-64 ..
  - cmake --build . --config RelWithDebInfo --target INSTALL
  - 7z a libdmusic-v%APPVEYOR_BUILD_VERSION%-win32-x64.zip C:/install_libdmusic_x86-64/*
  - appveyor PushArtifact libdmusic-v%APPVEYOR_BUILD_VERSION%-win32-x64.zip

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/5020e3cf2a1bbb5c8247
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

deploy:
  release: libdmusic-v$(appveyor_build_version)
  description: 'Automated build release'
  provider: GitHub
  auth_token:
    secure: PKQ8wyiF5mNTAWbKepUrcnec7bucnXJ/T+Ip1NfxblviD6BqamxMuSQI1Kk5mCm+
  artifact: /.*\.zip/
  draft: true
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
