version: 0.1.5.{build}
image:
  - Visual Studio 2017
  - Ubuntu1804

configuration:
  - Debug
  - Release
  - RelWithDebInfo

platform:
  - x86
  - x64

environment:
  matrix:
    - LINKING: static
    - LINKING: shared

matrix:
  exclude:
    - image: Ubuntu1804
      platform: x86
    - image: Ubuntu1804
      LINKING: static
    - image: Ubuntu1804
      configuration: Debug
    - image: Ubuntu1804
      configuration: RelWithDebInfo
    - configuration: RelWithDebInfo
      LINKING: static

  allow_failures:
    - configuration: Debug
      LINKING: static

for:
-
  matrix:
    only:
      - image: Ubuntu1804
  
  cache:
    - vcpkg

  install:
    - sudo apt update
    - sudo apt install -y libasound2-dev libsndfile1-dev
    - git config --global user.name "Anonymous"
    - git config --global user.email "anon@example.org"
    - git clone https://github.com/Microsoft/vcpkg.git || true
    - cd vcpkg
    - git fetch
    - git pull
    - git remote add regoth https://github.com/REGoth-project/vcpkg.git || true
    - git fetch regoth
    - git merge --no-edit regoth/rtaudio || true
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install args rtaudio sf2cute
    - cd ..

  build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build .
-
  matrix:
    only:
      - image: Visual Studio 2017
  
  cache:
    - c:\tools\vcpkg\installed\

  install:
    - git config --global user.name "Anonymous"
    - git config --global user.email "anon@example.org"
    - cd C:\tools\vcpkg
    - git remote add regoth https://github.com/REGoth-project/vcpkg.git
    - git fetch regoth
    - git merge --no-edit regoth/sf2cute regoth/rtaudio
    - .\bootstrap-vcpkg.bat
    - cd %APPVEYOR_BUILD_FOLDER%
    - set TRIPLET=%PLATFORM%-windows
    - IF "%LINKING%"=="static" (set TRIPLET=%TRIPLET%-static)
    - vcpkg install --triplet %TRIPLET% args rtaudio sf2cute libsndfile[core]

  build_script:
    - set GENERATOR=Visual Studio 15 2017
    - IF %PLATFORM%==x64 (set GENERATOR=%GENERATOR% Win64)
    - IF "%LINKING%"=="shared" ( set ADDITIONAL=-DBUILD_SHARED_LIBS=ON )
    - IF "%LINKING%"=="static" ( set ADDITIONAL=-DDMUSIC_FORCE_STATIC_CRT=ON )
    - set ADDITIONAL=%ADDITIONAL% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/install
    - mkdir build
    - cd build
    - cmake %ADDITIONAL% -DVCPKG_TARGET_TRIPLET=%TRIPLET% -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake .. -G "%GENERATOR%"
    - cmake --build . --config %CONFIGURATION% --target INSTALL
    - robocopy C:/Tools/vcpkg/installed/%TRIPLET%/bin %APPVEYOR_BUILD_FOLDER%/install/bin *.dll

  after_build:
    - 7z a %APPVEYOR_BUILD_FOLDER%/libdmusic.zip %APPVEYOR_BUILD_FOLDER%/install/*
    - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/libdmusic.zip
