version: 0.1.5.{build}
image:
- Visual Studio 2017
- Ubuntu1804

platform:
  - x86
  - x64

for:
-
  matrix:
    only:
      - image: Ubuntu1804
  
  cache:
    - vcpkg

  install:
    - sudo apt install -y libasound2-dev libsndfile1-dev
    - git config --global user.name "Anonymous"
    - git config --global user.email "anon@example.org"
    - git clone https://github.com/REGoth-project/vcpkg.git || true
    - cd vcpkg
    - git merge --no-edit origin/sf2cute origin/rtaudio || true
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install args rtaudio sf2cute
    - cd ..

  build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build .
-
  matrix:
    only:
      - image: Visual Studio 2017
  
  cache:
    - vcpkg

  install:
    - IF NOT EXIST vcpkg ( ./ci/configure_vcpkg.bat )
    - .\vcpkg.exe install args rtaudio sf2cute libsndfile
    - cd ..

  build_script:
    - mkdir build
    - cd build
    - if %PLATFORM%==x86 ( cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake .. )
    - if %PLATFORM%==x64 ( cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 15 2017 Win64" .. )
    - cmake --build . --config Release
    - cmake --build . --config Debug
    - cmake --build . --config RelWithDebInfo
